application: v2ex
version: alpha
runtime: python27
api_version: 1
threadsafe: false

derived_file_type:
- python_precompiled

libraries:
- name: PIL
  version: "latest"
- name: webapp2
  version: "latest"
- name: django
  version: "latest"
- name: jinja2
  version: "latest"

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /apple-touch-icon.png
  static_files: static/img/apple-touch-icon.png
  upload: static/img/apple-touch-icon.png
    
- url: /static
  static_dir: static

- url: /mapreduce(/.*)?
  script: mapreduce/main.APP
  login: admin
 
- url: /_ah/mail/.+
  script: mail.application
  login: admin

- url: /_ah/xmpp/.+
  script: xmpp.application
  login: admin

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /add/star/(.*)
  script: app.application
  login: admin

- url: /minus/star/(.*)
  script: app.application
  login: admin

- url: /money/(.*)
  script: money.application

- url: /sso/(.*)
  script: sso.application

- url: /.*
  script: app.application

inbound_services:
- mail
- xmpp_message

skip_files:
- node_modules
- bower_components
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
